- name: Launch a custom EC2 instance
  hosts: localhost
  remote_user: ec2-user
  vars_files:
  - ../config/aws.yml
  tasks:
    - name: Get latest AMI ID
      command: ../util/get-latest-ami.sh
      register: latestami

    - debug: var=latestami.stdout

    - name: Create instance
      ec2:
        image: "{{ latestami.stdout }}"
        instance_profile_name: EC2FULL
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        vpc_subnet_id: subnet-06221544c996c7042
        instance_tags:
          Name: custom
        groups: ['default', 'allow_ssh']
        instance_type: t2.micro
        wait: yes
        user_data: |
          #!/bin/bash
          echo "hellp"
          yum update -y
          yum install -y squid
          chkconfig squid on
      register: new_instance

    - name: Add new instance to Host group
      add_host:
        hostname: "{{ item.public_ip }}"
        group: new_instances
      with_items: "{{ new_instance.instances }}"

    - name: debug
      debug: var=new_instance

- name: Do stuff on remote
  hosts: new_instances
  remote_user: ec2-user
  tags: ["configure"]
  become: true

  tasks:
    - name: Create temp file
      file:
        path: /home/ec2-user/myfile.txt
        state: touch
        owner: ec2-user
        group: ec2-user
        mode: 0644

    - name: Echo some stuff to file
      shell: >-
        echo "here is my first file" > /home/ec2-user/myfile.txt

    # - name: Format instance
# 
    # - name: Mount instance to /data
# 
    # - name: Write file to /data 
# 
    # - name: Create snapshot of drive
# 
    # - name: Write file to /data
# 
    # - name: Query snapshot ID
# 
    # - name: Detach old volume from instance
# 
    # - name: Create volume from snapshot ID and attach to instance
# 
    # - name: Mount new volume to same directory

# 
    # - debug: var=instance_info
      # tags: always
# 
    # - debug: var=instance_info.instances[0].network_interfaces[0].association.public_ip
      # tags: always