---
- name: Create SQS queues
  hosts: localhost

  tasks:
    - name: Create first queue
      sqs_queue:
        name: my_queue
        region: us-east-2
        default_visibility_timeout: 120
        message_retention_period: 86400
        maximum_message_size: 1024
        delivery_delay: 30
        receive_message_wait_time: 20
        policy: 
